### ISSUE TITLE
實作 des crypt Golang 版本

### ISSUE THREAD

**Issue by PichuChen** [PichuChen/go-bbs#13]
目前 PTT 以及多數 BBS 將密碼進行 Hash 的演算法應該是基於 DES 的演算法。
然而這個演算法並沒辦法使用 DES 直接實作。

雖然原本的 C 程式碼裡面有 fcrypt 可以用，不過如果直接靜態編譯進來可能未來會有版權問題。
替代的方案是使用作業系統中可能原本就有的 crypt 函式，在現代電腦上效能可能差不多了。

另外的問題是無論是 fcrypt 或者是 crypt 都有回傳靜態記憶體位置的問題，網路上有看到用純 Golang 實作的版本，也有套件化，所以搞不好用該版本會更好？

**Comment by chhsiao1981** [comment]
#5  done.
