### ISSUE TITLE
確認 Master 以及 Develop Branch 合併時機

### ISSUE THREAD

**Issue by PichuChen** [PichuChen/go-bbs#17]
如標題，目前在送 PR 的時候基本上都是送往 Master Branch

初期可以這樣做，後期可能為了穩定度和開發方便可能需要分Branch

基本上有兩個方向，一個是另外開Develop Branch，另外一個則是另外開 Release Branch，相關的討論再請大家討論。

**Comment by chhsiao1981** [comment]
開發是 Master Branch.

stable-release 是用 git tag v[major].[minor].[patch].

每次開發過程:

1. 確定要開發什麼 feature. 根據這個 feature 決定要叫什麼 branch
2. git checkout master && git pull (從 master 拿到最新 available 結果)
3. git branch [branch] && git checkout [branch]
4. (programming / testing)
5. PR 回 Master.

**Comment by PichuChen** [comment]
目前因為有個開發伺服器，所以應該會需要一個給這個開發伺服器Depoly用的branch

我會先叫他 develop 假如有需要更動再說，那之後大家的程式碼應該就先merge到develop這樣？

**Comment by PichuChen** [comment]
太久沒有後續了，先關閉。
