### ISSUE TITLE
解析我的最愛檔案

### ISSUE THREAD

**Issue by PichuChen** [PichuChen/go-bbs#21]
我的最愛檔案 .fav 的測試檔已經上傳了，該使用者應該有 test 以及 ALLPOST 兩個最愛。

檔案位置位於
https://github.com/PichuChen/go-bbs/tree/master/testcase/fav

相關的Header 位置位於
https://github.com/ptt/pttbbs/blob/af507e0029c4e6b3a564ec98328ffe7cd7fd16be/mbbsd/fav.c
https://github.com/ptt/pttbbs/blob/af507e0029c4e6b3a564ec98328ffe7cd7fd16be/include/fav.h

**Comment by PichuChen** [comment]
#16

**Comment by ifanchu** [comment]
我可以接這個issue

**Comment by PichuChen** [comment]
> 我可以接這個issue

麻煩了！

**Comment by PichuChen** [comment]
從二進位解析成 golang struct 的部分好了，接下來是 golang struct 轉回二進位的部分。

**Comment by ifanchu** [comment]
I can take this as well.
