### ISSUE TITLE
確認 JWT 實作細節以及實作 JWT Token

### ISSUE THREAD

**Issue by PichuChen** [PichuChen/go-bbs#24]
目前在Access Token 的設計上應該會採用 JWT Token

已知裡面會有 User ID 作為簽發主體

現在看還需不需要多塞什麼東西以利Client端利用，以及有效時間大約多久？三十分鐘？五分鐘？

**Comment by ifanchu** [comment]
Just a thought. 

I think the ECDSA private key should not be hardcoded in the code. It should be read from a file instead given the file has most strict access permission. This way the server can invalidate all tokens at any time. 

Also this ECDSA private key is only being used to sign the JWT, I don't see why it has to be an ECDSA private key. If there is a specific reason of doing this, we should provide justification and comment in the code.

**Comment by PichuChen** [comment]
目前 private key 在這份是直接寫在程式碼當中，因為這份的 serverlet 的性質比較接近範例。

在 PTT APP 後端使用的版本會以 https://github.com/Ptt-official-app/Ptt-backend 這份為主，因此 JWT 部分可能直接移過去那邊討論比較好。
