### ISSUE TITLE
新增 board header parser

### ISSUE THREAD

**Issue by cftang0827** [PichuChen/go-bbs#7]
預計要做 board header parser 以及 unit test 的部分
會修改的程式碼包含
`board.go` 
`board_test.go`

只會做最初步的parser，基本上就是按照 `pttstruct.h` 裡面的`boardheader_t`結構去實作

**Comment by cftang0827** [comment]
請指派給我！謝謝

**Comment by PichuChen** [comment]
請問目前這個有下文嗎？
